language: cpp

addons:
  apt:
    update: true
    packages:
      - cppcheck
      - valgrind
      - cmake
      - libgtest-dev
      - lcov
      - qtbase5-dev
      - qtdeclarative5-dev

before_install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt || (cat CMakeFiles/CMakeError.log && CMakeFiles/CMakeOutput.log)
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

install:
  - pip install codecov

script:
#  - cppcheck src/*.c include/*.h
  - cd client
  - mkdir build
  - cd build
  - cmake .. && make
  - ./client
  - ./tests/tst
#  - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all --track-origins=yes ./tests/tst
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - make clean
  - codecov

  - cd ../server
  - mkdir build
  - cd build
  - cmake .. && make
  - ./net_mock_test

after_success:
  - bash <(curl -s https://codecov.io/bash)